# Generated by Django 2.1.7 on 2019-03-16 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_project', '0003_auto_20190316_0643'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenroll',
            old_name='fresh_first_sem',
            new_name='yr1_sem1',
        ),
        migrations.RenameField(
            model_name='courseenroll',
            old_name='fresh_second_sem',
            new_name='yr1_sem2',
        ),
        migrations.RenameField(
            model_name='courseenroll',
            old_name='jun_first_sem',
            new_name='yr2_sem1',
        ),
        migrations.RenameField(
            model_name='courseenroll',
            old_name='jun_second_sem',
            new_name='yr2_sem2',
        ),
        migrations.RenameField(
            model_name='courseenroll',
            old_name='sen_first_sem',
            new_name='yr3_sem1',
        ),
        migrations.RenameField(
            model_name='courseenroll',
            old_name='sen_second_sem',
            new_name='yr3_sem2',
        ),
        migrations.RenameField(
            model_name='courseenroll',
            old_name='soph_first_sem',
            new_name='yr4_sem1',
        ),
        migrations.RenameField(
            model_name='courseenroll',
            old_name='soph_second_sem',
            new_name='yr4_sem2',
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='course',
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_project.CourseData'),
        ),
        migrations.RemoveField(
            model_name='courseenroll',
            name='user',
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
