# Generated by Django 2.1.7 on 2019-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedata',
            name='name',
        ),
        migrations.AddField(
            model_name='coursedata',
            name='course_dept',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='course_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='course_title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
