# Generated by Django 2.1.7 on 2019-03-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_project', '0002_auto_20190305_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='course_creds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='course_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='course_subject',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
