# Generated by Django 2.1.7 on 2019-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_project', '0004_auto_20190318_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='course_num',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
