# Generated by Django 2.1.7 on 2019-03-17 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_courses', '0002_auto_20190316_0850'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr1_sem1', models.BooleanField(default=False)),
                ('yr1_sem2', models.BooleanField(default=False)),
                ('yr2_sem1', models.BooleanField(default=False)),
                ('yr2_sem2', models.BooleanField(default=False)),
                ('yr3_sem1', models.BooleanField(default=False)),
                ('yr3_sem2', models.BooleanField(default=False)),
                ('yr4_sem1', models.BooleanField(default=False)),
                ('yr4_sem2', models.BooleanField(default=False)),
                ('extra_sem', models.BooleanField(default=False)),
                ('course2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_courses.CourseEnroll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
