# Generated by Django 2.1.7 on 2019-03-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delete_courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseremove',
            name='course2',
        ),
        migrations.RemoveField(
            model_name='courseremove',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseRemove',
        ),
    ]
